name: Issue matching auto-closer
description: Automatically close issues based on regexs matching.
author: arkon
branding:
  icon: alert-circle
  color: red
inputs:
  repo-token:
    required: true
    description: GitHub token
  rules:
    required: true
    description: |
      A JSON-compliant string containing a list of rules, where a rule consists of:

      {
        type: 'title' | 'body';          // Part to run regex against.
        regex: string;                   // Pattern which if matched closes the issue.
        ignoreCase: boolean | undefined; // Defines if the regex will be case insensitive.
        message: string;                 // Message to post when closing the issue.
                                         // You can use {match} as a placeholder to the first match.
      }
runs:
  using: node12
  main: dist/index.js
